# Generated by Django 4.2.16 on 2025-01-27 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='category',
        ),
    ]
